# Generated by Django 4.2.4 on 2023-08-08 23:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SmartFan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_on", models.BooleanField(default=False)),
                ("speed", models.PositiveIntegerField(default=0)),
                ("rotating", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="SmartLight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_on", models.BooleanField(default=False)),
                ("brightness", models.PositiveIntegerField(default=0)),
                ("room", models.CharField(max_length=100)),
            ],
        ),
    ]
